export const url = {
  landingPage: "/",
  home: "/home",
  market: "/marketplace",
  singleMarket: "/marketplace/:Id",
  auction: "/auction",
  singleAuction: "/auction/:auctionId",
  drops: "/drops",
  search: "/search",
  singleSearch: "/search/:searchId",
  cart: "/yourcart",
  notify: "/notifications",
  shipping: "/shippingDetails",
  payment: "/paymentdetails",
  completed: "/thankYou",
};
